module SqlAccount 
  class Invoice < Record

    self.table_name = "sl_iv"

  end
end

#<SqlAccount::Invoice:0x00007f81b98a1690
#  dockey: 1,
#  docno: "IV-00001",
#  docnoex: nil,
#  docdate: "2026-06-11",
#  postdate: "2026-06-11",
#  taxdate: "2026-06-11",
#  eiv_utc: nil,
#  eiv_received_utc: nil,
#  eiv_validated_utc: nil,
#  code: "300-T0001",
#  companyname: "THAI TEA TRADING",
#  address1: "No 45, Jalan Batu Tiga Klang,",
#  address2: "42000, Pelabuhan Klang, Selangor.",
#  address3: nil,
#  address4: nil,
#  postcode: nil,
#  city: nil,
#  state: nil,
#  country: "",
#  phone1: "03-3816 1027",
#  mobile: nil,
#  fax1: nil,
#  attention: "Mr. Leonard",
#  area: "Selangor",
#  agent: "Yuki",
#  project: "----",
#  terms: "60 Days",
#  currencycode: "----",
#  currencyrate: 0.1e1,
#  shipper: "----",
#  description: "Sales",
#  cancelled: false,
#  status: 0,
#  docamt: 0.8e3,
#  localdocamt: 0.8e3,
#  d_amount: 0.0,
#  validity: nil,
#  deliveryterm: nil,
#  cc: nil,
#  docref1: nil,
#  docref2: nil,
#  docref3: nil,
#  docref4: nil,
#  branchname: "BILLING",
#  daddress1: "No 45, Jalan Batu Tiga Klang,",
#  daddress2: "42000, Pelabuhan Klang, Selangor.",
#  daddress3: nil,
#  daddress4: nil,
#  dpostcode: nil,
#  dcity: nil,
#  dstate: nil,
#  dcountry: "",
#  dattention: "Mr. Leonard",
#  dphone1: "03-3816 1027",
#  dmobile: nil,
#  dfax1: nil,
#  taxexemptno: nil,
#  salestaxno: nil,
#  servicetaxno: nil,
#  tin: nil,
#  idtype: 0,
#  idno: nil,
#  tourismno: nil,
#  sic: nil,
#  incoterms: nil,
#  submissiontype: 0,
#  irbm_status: 0,
#  irbm_internalid: nil,
#  irbm_uuid: nil,
#  irbm_longid: nil,
#  eivrequest_uuid: nil,
#  peppol_uuid: nil,
#  peppol_docuuid: nil,
#  businessunit: nil,
#  attachments: nil,
#  note: nil,
#  approvestate: nil,
#  transferable: true,
#  updatecount: nil,
#  printcount: 0,
#  lastmodified: 1782147961> 

